#!/bin/sh /etc/rc.common
 
START=97
STOP=4
USE_PROCD=1
 
start_service() {
        procd_open_instance
        procd_set_param command /root/CAKE-autorate/CAKE-autorate.sh
        # uncomment if you want procd to restart your script if it terminated for whatever reason
        #procd_set_param respawn   
        procd_close_instance
}
