#!/bin/sh /etc/rc.common
# Copyright (C) 2007 OpenWrt.org

export PATH=/usr/sbin:/usr/bin:/sbin:/bin
export HOME=/root

exec &> /tmp/sqm-autorate.log

START=97
STOP=4

start() {
        /root/sqm-autorate.sh&
}

stop() {
        ps | grep sqm-autorate.sh | grep -v grep | awk '{print $1}' | xargs kill
}
